spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:test
    username: test
    driver-class-name: org.h2.Driver

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

crypt:
  key: "Edu Mirmil Study"